name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      VERSION: '3.0.1'
      SERVERPOD_PASSWORD_database: 'EAR3hNdj0t3rOf-nO4evNgdy3VHMqb_r'
      SERVERPOD_PASSWORD_redis: 'B0TdapHwtlTnJmR2_1DHDG7r_H3l_di_'

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'

      - name: Start containers
        working-directory: example_server
        run: docker compose up --build -d

      - name: Install dependencies
        working-directory: example_server
        run: dart pub get

      - name: Install Serverpod CLI
        working-directory: example_server
        run: dart pub global activate serverpod_cli $VERSION

      - name: Run Serverpod generator
        working-directory: example_server
        run: serverpod generate

      - name: Run tests
        working-directory: example_server
        run: dart test

      - name: Stop containers
        if: always()
        working-directory: example_server
        run: docker compose down -v
