name: serverpod_admin_client
description: Starting point for a Serverpod module client.
version: 1.0.2
# homepage: https://www.example.com
homepage: https://github.com/AdamMusa/serverpod_admin

environment:
  sdk: '>=3.5.0 <4.0.0'
dependencies:
  serverpod_client: 2.9.1
