name: serverpod_wire
description: A CLI tool for generating Serverpod CRUD boilerplate from templates
version: 0.1.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0

executables:
  serverpod_wire:

