name: example_client
description: Starting point for a Serverpod client.

environment:
  sdk: '^3.8.0'

dependencies:
  serverpod_auth_idp_client: 3.0.1
  # serverpod_admin_client:
  #   path: ../../serverpod_admin_client
  serverpod_client: 3.0.1

